keys:
  - &lelgenio-gpg 0FECE8316E74BA6F44EFC21A2F8F21CE8721456B
  - &lelgenio-ssh age1zrgu7w8059xydagm60phnffghvfe9h2ca58cx8qwagqpyfuvs9fqw79c8h
  - &monolith-ssh age1ecyynwv93lfu7crjjp8l47defv07quzfzaktwurpep7jc9eha5pscg7lrw
  - &phantom-ssh age1m4mqcd2kmuhfr8a22rvh02c68jkakhdfmuqgtusuv0czk4jvna7sz79p3y

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *lelgenio-gpg
      age:
      - *lelgenio-ssh
      - *monolith-ssh
  - path_regex: secrets/monolith/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *lelgenio-gpg
      age:
      - *lelgenio-ssh
      - *monolith-ssh
  - path_regex: secrets/phantom/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *lelgenio-gpg
      age:
      - *lelgenio-ssh
      - *phantom-ssh
