#!/bin/sh

./switch \
    --option extra-substituters "http://nixcache.lelgenio.1337.cx:5000" \
    --option extra-trusted-public-keys "nixcache.lelgenio.1337.cx:HZCwDaM39BOF+MLuviMQTUrz3rBWLTLV9H+GV4zcxVI=" \
    "$@"
