#!/bin/sh
output=$(printf "HDMI\nHeadphones" | wdmenu -i -p "Output:")
vol=$(pamixer --get-volume)
case "$output" in
    HDMI)
        pactl set-default-sink alsa_output.pci-0000_07_00.1.hdmi-stereo-extra1
        ;;
    Headphones)
        pactl set-default-sink alsa_output.pci-0000_09_00.4.analog-stereo
        ;;
esac
pamixer --set-volume "$vol"
