#!/bin/sh

CLASS="terminal"

while test $# -gt 0;do
    case $1 in
        -c|--class)
            shift
            CLASS=$1
            shift
            ;;
        *)
            break
            ;;
    esac
done

exec alacritty --class "$CLASS" "$@"
